#!/usr/bin/env python3

import os
import sys

GST_VALIDATE_LAUNCHER_COMMAND = "gst-validate-launcher"

if (os.system(GST_VALIDATE_LAUNCHER_COMMAND + " -h > %s 2>&1" % os.devnull) != 0):
    print("Make sure to install gst-validate: http://cgit.freedesktop.org/gstreamer/gst-devtools/tree/validate/"
          " before running the testsuite")
    sys.exit(127)

sys.exit(os.system("GST_VALIDATE_APPS_DIR=%s %s %s %s"
         % (os.path.abspath(os.path.join(os.path.dirname(__file__))),
            GST_VALIDATE_LAUNCHER_COMMAND,
            os.path.join(os.path.abspath(os.path.join(os.path.dirname(__file__))), "pitivi.py"),
            ' '.join(sys.argv[1:]))))
