test_list = ["Let's begin with quick overview",
             "Here Comes Your \n Project Title.",
             "To save your project \n you have this. ",
             "When you are done \n Here you have all your \n Export settings. ",
             "Here you have your menu items. ",
             "Undo Button.\n or you can press \n[ctrl]+Z. ",
             "Redo Button.\n or you can press \n[ctrl]+[shift]+Z. ",
             "Ok! now let's \nbegin with Viewer",
                 "This is your \nmedia playback. ",
                 "Seek to start",
                 "Seek back \none second",
                 "Play/Pause",
                 "Seek forward \none second",
                 "Seek to end",
                 "You can also Undock \n viewer by this button. ",
                 "Current position",
                 "Ok! now let's begin\n with timeline",
             "Here is your timeline.",
             "From here you can Zoom \n timeline for more clearity. ",
             "To add Layers",
             "You can cut/join/copy \n clips from these. ",
             "These markers point to frames,\n if you zoom in you can see them! ",
             "Ok, now let's\n move to media and \neffects part",
                 "Here you can view \n your imported media.",
                 "By this button you can \n import your favourite media.",
                 "From you can set your clip Properties",
                 "Show clips as List/Grid",
             "And now comes the\n coolest part \n [ Effects ]",
             "Here you have all your \n Effects and Filters. ",
             "You can also \nadd Music/Audio",
             "We have a \nlot of them!",
             "Cool right!",
                 "I hope it was \n help helpfull!",
                 "Wait! That's not it.",
                 "For more productivity \n we have  \n shortcuts for you \n Just press [ctrl]+F1 \n to see",
                 "Till the time you \n explore these. ",
                 "You will have more \n Features and Utilities. ",
                 "For additional Help \n you can also refer to \n User Manual provided. ",
                 "Thank you!"
                 ]
