test_list = ["Here Comes Your \n Project Title.",
             "Here you can view \n your imported media.",
             "By this button you can \n import your favourite media.",
             "Here you have all your \n Effects and Filters. ",
             "Here you have all \n your clip properties \n adjustments",
             # "From here you can \n apply transition. ",
             # "From here you can \n create/edit your title. ",
             "This is your media playback. ",
             "You can also Undock \n viewer by this button. ",
             "Here is your timeline. ",
             "You can cut/join/copy \n clips from these. ",
             "From here you can Zoom \n timeline for more clearity. ",
             "To save your project \n you have this. ",
             "When you are done \n Here you have all your \n Export settings. ",
             "Here you have your menu items. ",
             "Undo Button.\n or you can press \n[ctrl]+Z. ",
             "Redo Button.\n or you can press \n[ctrl]+[shift]+Z. ",

             # are for the interactive intro

             # "Cool right!",
             # "Ok let's perform \n some tasks",
             # "Import Clips \n from here",
             # "Good!",
             # "Now you see there isin't \n any prview on Viewer",
             # "So for that \n select and drag clips \n to the timeline",
             # "Now you see it appears on the viewer",
             # "Now let's apply some Effects to our clip",
             # "Select and drag some \n effects from here \n to the clip in timeline",
             # "Boom!!",
             # "You see how magically it \n affects your clip",
             # "We have dozens of Effects \n for you and many \n more on the way"
             # "Try playing your clip ",
             # "Cool right ?",
             # "As I said you can \n undock viewer  \n Let's do it",
             # "To return Back you\n just need to close \n the undocked viewer",
             # "Easy right ?"
             # "You can also transform \n clip by selecting \n it from viewer",
             "Wait! That's not it.",
             "For more productivity \n we have  \n shortcuts for you \n Just press [ctrl]+F1 \n to see",
             "Till the time you \n explore these. ",
             "You will have more \n Features and Utilities. ",
             "For additional Help \n you can also refer to \n User Manual provided. ",
             "Thank you!"]
